import { Container } from "../Container";
import { PartialContainer } from "../PartialContainer";

// These chains are written out literally on purpose. A type-level helper can build the same Services type, but only
// real method calls exercise how TypeScript instantiates each call's return type, which is where long chains used to
// exceed the instantiation depth limit (TS2589). Before the fixes a Container chain failed at 51 registrations and a
// PartialContainer chain with an unresolved dependency failed at 60. The chains stop at 80 because, up to
// TypeScript 5.8, overload resolution re-instantiates inferred type arguments and a chain that starts from an
// object-literal type such as fromObject({}) still fails at ~100 there; TypeScript 5.9 compiles 400.
// https://github.com/Snapchat/ts-inject/issues/27
describe("deep literal registration chains", () => {
  test("Container.fromObject({}) followed by 80 providesValue calls", () => {
    const container = Container.fromObject({})
      .providesValue("s0", 0)
      .providesValue("s1", 1)
      .providesValue("s2", 2)
      .providesValue("s3", 3)
      .providesValue("s4", 4)
      .providesValue("s5", 5)
      .providesValue("s6", 6)
      .providesValue("s7", 7)
      .providesValue("s8", 8)
      .providesValue("s9", 9)
      .providesValue("s10", 10)
      .providesValue("s11", 11)
      .providesValue("s12", 12)
      .providesValue("s13", 13)
      .providesValue("s14", 14)
      .providesValue("s15", 15)
      .providesValue("s16", 16)
      .providesValue("s17", 17)
      .providesValue("s18", 18)
      .providesValue("s19", 19)
      .providesValue("s20", 20)
      .providesValue("s21", 21)
      .providesValue("s22", 22)
      .providesValue("s23", 23)
      .providesValue("s24", 24)
      .providesValue("s25", 25)
      .providesValue("s26", 26)
      .providesValue("s27", 27)
      .providesValue("s28", 28)
      .providesValue("s29", 29)
      .providesValue("s30", 30)
      .providesValue("s31", 31)
      .providesValue("s32", 32)
      .providesValue("s33", 33)
      .providesValue("s34", 34)
      .providesValue("s35", 35)
      .providesValue("s36", 36)
      .providesValue("s37", 37)
      .providesValue("s38", 38)
      .providesValue("s39", 39)
      .providesValue("s40", 40)
      .providesValue("s41", 41)
      .providesValue("s42", 42)
      .providesValue("s43", 43)
      .providesValue("s44", 44)
      .providesValue("s45", 45)
      .providesValue("s46", 46)
      .providesValue("s47", 47)
      .providesValue("s48", 48)
      .providesValue("s49", 49)
      .providesValue("s50", 50)
      .providesValue("s51", 51)
      .providesValue("s52", 52)
      .providesValue("s53", 53)
      .providesValue("s54", 54)
      .providesValue("s55", 55)
      .providesValue("s56", 56)
      .providesValue("s57", 57)
      .providesValue("s58", 58)
      .providesValue("s59", 59)
      .providesValue("s60", 60)
      .providesValue("s61", 61)
      .providesValue("s62", 62)
      .providesValue("s63", 63)
      .providesValue("s64", 64)
      .providesValue("s65", 65)
      .providesValue("s66", 66)
      .providesValue("s67", 67)
      .providesValue("s68", 68)
      .providesValue("s69", 69)
      .providesValue("s70", 70)
      .providesValue("s71", 71)
      .providesValue("s72", 72)
      .providesValue("s73", 73)
      .providesValue("s74", 74)
      .providesValue("s75", 75)
      .providesValue("s76", 76)
      .providesValue("s77", 77)
      .providesValue("s78", 78)
      .providesValue("s79", 79);

    const first: number = container.get("s0");
    const last: number = container.get("s79");
    expect([first, last]).toEqual([0, 79]);
  });

  test("PartialContainer.fromObject({}) followed by 80 provides calls that all depend on an unprovided token", () => {
    const partial = PartialContainer.fromObject({})
      .provides("s0", ["dep"] as const, (dep: number) => dep + 0)
      .provides("s1", ["dep"] as const, (dep: number) => dep + 1)
      .provides("s2", ["dep"] as const, (dep: number) => dep + 2)
      .provides("s3", ["dep"] as const, (dep: number) => dep + 3)
      .provides("s4", ["dep"] as const, (dep: number) => dep + 4)
      .provides("s5", ["dep"] as const, (dep: number) => dep + 5)
      .provides("s6", ["dep"] as const, (dep: number) => dep + 6)
      .provides("s7", ["dep"] as const, (dep: number) => dep + 7)
      .provides("s8", ["dep"] as const, (dep: number) => dep + 8)
      .provides("s9", ["dep"] as const, (dep: number) => dep + 9)
      .provides("s10", ["dep"] as const, (dep: number) => dep + 10)
      .provides("s11", ["dep"] as const, (dep: number) => dep + 11)
      .provides("s12", ["dep"] as const, (dep: number) => dep + 12)
      .provides("s13", ["dep"] as const, (dep: number) => dep + 13)
      .provides("s14", ["dep"] as const, (dep: number) => dep + 14)
      .provides("s15", ["dep"] as const, (dep: number) => dep + 15)
      .provides("s16", ["dep"] as const, (dep: number) => dep + 16)
      .provides("s17", ["dep"] as const, (dep: number) => dep + 17)
      .provides("s18", ["dep"] as const, (dep: number) => dep + 18)
      .provides("s19", ["dep"] as const, (dep: number) => dep + 19)
      .provides("s20", ["dep"] as const, (dep: number) => dep + 20)
      .provides("s21", ["dep"] as const, (dep: number) => dep + 21)
      .provides("s22", ["dep"] as const, (dep: number) => dep + 22)
      .provides("s23", ["dep"] as const, (dep: number) => dep + 23)
      .provides("s24", ["dep"] as const, (dep: number) => dep + 24)
      .provides("s25", ["dep"] as const, (dep: number) => dep + 25)
      .provides("s26", ["dep"] as const, (dep: number) => dep + 26)
      .provides("s27", ["dep"] as const, (dep: number) => dep + 27)
      .provides("s28", ["dep"] as const, (dep: number) => dep + 28)
      .provides("s29", ["dep"] as const, (dep: number) => dep + 29)
      .provides("s30", ["dep"] as const, (dep: number) => dep + 30)
      .provides("s31", ["dep"] as const, (dep: number) => dep + 31)
      .provides("s32", ["dep"] as const, (dep: number) => dep + 32)
      .provides("s33", ["dep"] as const, (dep: number) => dep + 33)
      .provides("s34", ["dep"] as const, (dep: number) => dep + 34)
      .provides("s35", ["dep"] as const, (dep: number) => dep + 35)
      .provides("s36", ["dep"] as const, (dep: number) => dep + 36)
      .provides("s37", ["dep"] as const, (dep: number) => dep + 37)
      .provides("s38", ["dep"] as const, (dep: number) => dep + 38)
      .provides("s39", ["dep"] as const, (dep: number) => dep + 39)
      .provides("s40", ["dep"] as const, (dep: number) => dep + 40)
      .provides("s41", ["dep"] as const, (dep: number) => dep + 41)
      .provides("s42", ["dep"] as const, (dep: number) => dep + 42)
      .provides("s43", ["dep"] as const, (dep: number) => dep + 43)
      .provides("s44", ["dep"] as const, (dep: number) => dep + 44)
      .provides("s45", ["dep"] as const, (dep: number) => dep + 45)
      .provides("s46", ["dep"] as const, (dep: number) => dep + 46)
      .provides("s47", ["dep"] as const, (dep: number) => dep + 47)
      .provides("s48", ["dep"] as const, (dep: number) => dep + 48)
      .provides("s49", ["dep"] as const, (dep: number) => dep + 49)
      .provides("s50", ["dep"] as const, (dep: number) => dep + 50)
      .provides("s51", ["dep"] as const, (dep: number) => dep + 51)
      .provides("s52", ["dep"] as const, (dep: number) => dep + 52)
      .provides("s53", ["dep"] as const, (dep: number) => dep + 53)
      .provides("s54", ["dep"] as const, (dep: number) => dep + 54)
      .provides("s55", ["dep"] as const, (dep: number) => dep + 55)
      .provides("s56", ["dep"] as const, (dep: number) => dep + 56)
      .provides("s57", ["dep"] as const, (dep: number) => dep + 57)
      .provides("s58", ["dep"] as const, (dep: number) => dep + 58)
      .provides("s59", ["dep"] as const, (dep: number) => dep + 59)
      .provides("s60", ["dep"] as const, (dep: number) => dep + 60)
      .provides("s61", ["dep"] as const, (dep: number) => dep + 61)
      .provides("s62", ["dep"] as const, (dep: number) => dep + 62)
      .provides("s63", ["dep"] as const, (dep: number) => dep + 63)
      .provides("s64", ["dep"] as const, (dep: number) => dep + 64)
      .provides("s65", ["dep"] as const, (dep: number) => dep + 65)
      .provides("s66", ["dep"] as const, (dep: number) => dep + 66)
      .provides("s67", ["dep"] as const, (dep: number) => dep + 67)
      .provides("s68", ["dep"] as const, (dep: number) => dep + 68)
      .provides("s69", ["dep"] as const, (dep: number) => dep + 69)
      .provides("s70", ["dep"] as const, (dep: number) => dep + 70)
      .provides("s71", ["dep"] as const, (dep: number) => dep + 71)
      .provides("s72", ["dep"] as const, (dep: number) => dep + 72)
      .provides("s73", ["dep"] as const, (dep: number) => dep + 73)
      .provides("s74", ["dep"] as const, (dep: number) => dep + 74)
      .provides("s75", ["dep"] as const, (dep: number) => dep + 75)
      .provides("s76", ["dep"] as const, (dep: number) => dep + 76)
      .provides("s77", ["dep"] as const, (dep: number) => dep + 77)
      .provides("s78", ["dep"] as const, (dep: number) => dep + 78)
      .provides("s79", ["dep"] as const, (dep: number) => dep + 79);
    const container = Container.providesValue("dep", 1).provides(partial);

    const first: number = container.get("s0");
    const last: number = container.get("s79");
    expect([first, last]).toEqual([1, 80]);
  });
});
